<div id="Our-Mission-Text">
    <h2>Our Mission</h2>
    <p>WiFinder mission is to connect the citizens of Brisbane with location data on where the closest Free Wifi-Location. To ensure they stay connected to the internet</p>
</div>
<div id="connect-with-us">
    <h2>Connect With Us On:</h2>
    <a href="" style="Color:White"><i class="fa fa-facebook-square fa-3x"></i></a>
    <a href="" style="Color:White"><i class="fa fa-instagram fa-3x"></i></a>
    <a href="" style="Color:White"><i class="fa fa-twitter-square fa-3x"></i></a>
</div>